[package]
name = "gaia"
version = "0.1.0"
authors = ["Alexandre Herve <alexandre.herve@dashlane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.42"
rand = "0.8.3"
